# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20170911_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(default='newname', max_length=140),
            preserve_default=False,
        ),
    ]
