# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_media_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='body_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_nl',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='upload',
            field=models.FileField(upload_to='%Y/%m/%d/'),
        ),
    ]
